import Head from 'next/head'


export default function Home() {
  return (
    <>
        <div>
          <Head>

            <title>Create Next App</title>

            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main >
            <h1>This is our AI app</h1>
            <img src='/favicon.ico'/>
            <h3>Name of my Pet</h3>
            <form>
              <input
              type='text'
              name='animal'
              placeholder='Enter an animal'
             />
              <input
              type='submit' />
            </form>
          </main>
        </div>
    </>
  )
}
