import Head from 'next/head'
import {useState} from 'react'


export default function Home() {

  const [count, setCounter] =useState(0);
  return (
    <>
        <div>
          <Head>

            <title>Create Next App</title>

            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main >
            <h1>This is our AI app</h1>
            <img src='/favicon.ico'/>
            <h3>Name of my Pet</h3>
            <p>You've used this app {count} times</p>
            <form>
              <input
              type='text'
              name='animal'
              placeholder='Enter an animal'
             />
              <input
              type='submit' onClick={(e)=> {
                e.preventDefault()
                if(count == 10) {
                  return console.log("You've reached your limit");
                }


                setCounter(count + 1)}}
              />
            </form>
          </main>
        </div>
    </>
  )
}
